<<<<<<< HEAD
services:
  neo4j:
    image: neo4j:5.16.0
    container_name: mental_health_neo4j
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./data/neo4j:/data
      - ./logs:/logs
    restart: unless-stopped
=======
services:
  neo4j:
    image: neo4j:5.16.0
    container_name: mental_health_neo4j
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./data/neo4j:/data
      - ./logs:/logs
    restart: unless-stopped
>>>>>>> 007909633b0dbd35d894a70cd8159a473e3c621e
